image: bradrydzewski/ruby:1.9.3
script:
  - bundle install --without development
  - gem update --system 2.1.11 # Temporary fix till rubygems works ok
  - bundle exec rspec spec
  - bundle exec rubocop
notify:
  email:
    recipients:
      - hajee@moretIA.com