language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  # - jruby-19mode
  # - rbx-19mode
bundler_args: --without development
# before_install:
#   -  gem update --system 2.1.11 # Temporary fix till rubygems works ok
script:
  - bundle exec rspec spec
# matrix:
#   allow_failures:
#     -rvm: jruby-19mode
gemfile:
  - gemfiles/gemfile.1.8.7
  - gemfiles/gemfile.1.9.3

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/gemfile.1.9.3
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: gemfiles/gemfile.1.8.7
